CREATE OR REPLACE FUNCTION noEmp_depto (
  id NUMBER
)
RETURN NUMBER
IS
  depto NUMBER;
BEGIN
  SELECT deptno INTO depto
  FROM emp
  WHERE empno = id;
  RETURN depto;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN NULL;
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(SQLERRM);
      RETURN NULL;
END;
